// Code generated by "stringer -type=Role,Direction"; DO NOT EDIT.

package directory

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Parent-0]
	_ = x[Working-1]
	_ = x[Child-2]
}

const _Role_name = "ParentWorkingChild"

var _Role_index = [...]uint8{0, 6, 13, 18}

func (i Role) String() string {
	if i >= Role(len(_Role_index)-1) {
		return "Role(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Role_name[_Role_index[i]:_Role_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Up-0]
	_ = x[Down-1]
}

const _Direction_name = "UpDown"

var _Direction_index = [...]uint8{0, 2, 6}

func (i Direction) String() string {
	if i >= Direction(len(_Direction_index)-1) {
		return "Direction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Direction_name[_Direction_index[i]:_Direction_index[i+1]]
}
